-- 部首表初始化数据（100条，逐条INSERT）
-- 来源: 汉字部首.xlsx
-- 仅填充有数据的字段，无数据字段通过后台补充

INSERT INTO `char_radical` (`id`, `radical`, `relation_id`, `evolution_desc`) VALUES (1, '厂', NULL, '“厂”是象形字，古文字模拟山崖的形状。本义是山崖。远古人类常靠山崖建房，所以“厂”部的字多与房屋建筑相关。');
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`, `evolution_desc`) VALUES (2, '亻', 3, '“人”是象形字，古文字模拟侧立的人形。“人”部的字多与跟人和人的活动相关，如称谓、德行、行为等。');
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`, `evolution_desc`) VALUES (3, '人', 2, '“人”在字左侧做偏旁时写作“亻”，“人”是象形字，古文字模拟侧立的人形。“亻”部的字多与跟人和人的活动相关，如称谓、德行、行为等。');
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`, `evolution_desc`) VALUES (4, '亠', NULL, '“亠”是一个汉字部件，叫“京字头”，由一点一横组成。它不是独立的象形字，而是在字形演变中形成的构字部件。亡、市、京、夜、充等字中都有“亠”的部件。');
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`, `evolution_desc`) VALUES (5, '冫', NULL, '“冫”是古文字模拟水凝结的样子，本义指水结成的固体，即“冰”最初的写法。“冫”部的字多与冰和寒冷相关。');
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`, `evolution_desc`) VALUES (6, '刂', NULL, '“刂”是“刀”在字右侧做偏旁时的变体。“刀”是象形字，甲骨文模拟刀的形状，本义指有锋刃的切割工具。“刂”部的字多与刀及切割动作相关。');
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`, `evolution_desc`) VALUES (7, '力', NULL, '“力”是象形字，古文字模拟耕地农具“耒”的形状，上部是柄，下部是齿刃。本义是耕田的农具。古人耕田需要用力，因此“力”引申为气力、力量。“力”部的字多与力量、功效相关。');
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`, `evolution_desc`) VALUES (8, '土', NULL, '“土”是象形字，古文字模拟地面上凸起的土块。本义是土壤、土地。“土”部的字大都跟土地以及用土做的东西相关。');
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`, `evolution_desc`) VALUES (9, '艹', NULL, '“艹”是“艸”的变体。“艸”是象形字，古文字模拟两棵小草的样子，做偏旁时写作“艹”。本义是草。现代汉字中“艸”不独立成字。“艹”部的字多与草本植物及其气味、色彩相关。');
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`, `evolution_desc`) VALUES (10, '口', NULL, '“口”是象形字，字形模拟张开的嘴的形状。本义指人嘴，后引申为一切事物的进出口，如：瓶口、关口、渡口。“口”部的字多与嘴巴及其功能相关。');
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`, `evolution_desc`) VALUES (11, '山', NULL, '“山”是象形字，古文字模拟连绵的群山，本义指地上高耸的山峰。“山”部的字多与山相关。');
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (12, '彳', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (13, '广', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (14, '门', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (15, '宀', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (16, '辶', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (17, '尸', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (18, '女', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (19, '马', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (20, '王', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (21, '木', 95);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (22, '犭', 94);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (23, '车', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (24, '攵', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (25, '日', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (26, '贝', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (27, '氵', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (28, '手', 29);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (29, '扌', 28);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (30, '月', 31);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (31, '月（肉）', 30);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (32, '火', 33);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (33, '灬', 32);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (34, '心', 35);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (35, '忄', 34);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (36, '石', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (37, '目', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (38, '禾', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (39, '疒', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (40, '穴', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (41, '耳', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (42, '页', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (43, '虫', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (44, '⺮', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (45, '衣', 46);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (46, '衤', 45);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (47, '米', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (48, '糸', 49);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (49, '纟', 48);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (50, '走', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (51, '酉', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (52, '足', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (53, '⻏', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (54, '言', 55);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (55, '讠', 54);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (56, '雨', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (57, '⻖', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (58, '钅', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (59, '饣', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (60, '又', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (61, '囗', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (62, '礻', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (63, '丷', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (64, '八', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (65, '勹', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (66, '夂', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (67, '皿', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (68, '士', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (69, '户', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (70, '方', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (71, '歹', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (72, '罒', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (73, '匚', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (74, '夕', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (75, '工', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (76, '欠', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (77, '牛', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (78, '刀', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (79, '殳', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (80, '白', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (81, '身', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (82, '隹', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (83, '鸟', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (84, '⺈', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (85, '冖', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (86, '彡', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (87, '斤', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (88, '音', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (89, '鱼', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (90, '卩', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (91, '寸', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (92, '牙', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (93, '龵', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (94, '犬', 22);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (95, '朩', 21);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (96, '水', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (97, '氺', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (98, '金', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (99, '非', NULL);
INSERT INTO `char_radical` (`id`, `radical`, `relation_id`) VALUES (100, '食', NULL);

