-- 汉字部首基础数据
-- 导入后状态为已发布(published)，可直接使用

INSERT INTO `char_radical` (`id`, `radical`, `stroke_num`, `evolution_desc`, `evolution_desc_translations`, `evolution_image_id`, `draft_content`, `create_by`, `update_by`, `update_time`, `create_time`, `edit_status`, `publish_status`, `status`) VALUES
(1, '厂', 2,
 '「厂」是象形字，古文字模拟山崖的形状。本义是山崖。远古人类常靠山崖建房，所以「厂」部的字多与房屋建筑相关。',
 NULL, NULL, NULL, 'admin', 'admin', NOW(), NOW(), 'published', 'published', 1),
(2, '亻', 2,
 '「人」在字左侧做偏旁时写作「亻」，「人」是象形字，古文字模拟侧立的人形。「亻」部的字多与人和人的活动相关，如称谓、德行、行为等。',
 NULL, NULL, NULL, 'admin', 'admin', NOW(), NOW(), 'published', 'published', 1),
(3, '人', 2,
 '「人」是象形字，古文字模拟侧立的人形。「人」部的字多与人和人的活动相关，如称谓、德行、行为等。',
 NULL, NULL, NULL, 'admin', 'admin', NOW(), NOW(), 'published', 'published', 1),
(4, '亠', 2,
 '「亠」是一个汉字部件，叫「京字头」，由一点一横组成。它不是独立的象形字，而是在字形演变中形成的构字部件。亡、市、京、夜、充等字中都有「亠」的部件。',
 NULL, NULL, NULL, 'admin', 'admin', NOW(), NOW(), 'published', 'published', 1),
(5, '冫', 2,
 '「冫」是古文字模拟水凝结的样子，本义指水结成的固体，即「冰」最初的写法。「冫」部的字多与冰和寒冷相关。',
 NULL, NULL, NULL, 'admin', 'admin', NOW(), NOW(), 'published', 'published', 1),
(6, '刂', 2,
 '「刂」是「刀」在字右侧做偏旁时的变体。「刀」是象形字，甲骨文模拟刀的形状，本义指有锋刃的切割工具。「刂」部的字多与刀及切割动作相关。',
 NULL, NULL, NULL, 'admin', 'admin', NOW(), NOW(), 'published', 'published', 1),
(7, '力', 2,
 '「力」是象形字，古文字模拟耕地农具「耒」的形状，上部是柄，下部是齿刃。本义是耕田的农具。古人耕田需要用力，因此「力」引申为气力、力量。「力」部的字多与力量、功效相关。',
 NULL, NULL, NULL, 'admin', 'admin', NOW(), NOW(), 'published', 'published', 1),
(8, '土', 3,
 '「土」是象形字，古文字模拟地面上凸起的土块。本义是土壤、土地。「土」部的字大都跟土地以及用土做的东西相关。',
 NULL, NULL, NULL, 'admin', 'admin', NOW(), NOW(), 'published', 'published', 1),
(9, '艹', 3,
 '「艹」是「艸」的变体。「艸」是象形字，古文字模拟两棵小草的样子，做偏旁时写作「艹」。本义是草。现代汉字中「艸」不独立成字。「艹」部的字多与草本植物及其气味、色彩相关。',
 NULL, NULL, NULL, 'admin', 'admin', NOW(), NOW(), 'published', 'published', 1),
(10, '口', 3,
 '「口」是象形字，字形模拟张开的嘴的形状。本义指人嘴，后引申为一切事物的进出口，如：瓶口、关口、渡口。「口」部的字多与嘴巴及其功能相关。',
 NULL, NULL, NULL, 'admin', 'admin', NOW(), NOW(), 'published', 'published', 1),
(11, '山', 3,
 '「山」是象形字，古文字模拟连绵的群山，本义指地上高耸的山峰。「山」部的字多与山相关。',
 NULL, NULL, NULL, 'admin', 'admin', NOW(), NOW(), 'published', 'published', 1);
